### ISSUE TITLE
MultiScreen command

### ISSUE THREAD

**Issue by lalitaalaalitah** [splash-cli/splash-cli#109]
Hello,
I'm on macOS and I run splash through a script at regular intervals.

I was able to use flag: --screen in previous version to specify screen for a specific wallpaper. It appears that v4 doesn't recognize this command and throw and error `Error: unknown flag: --screen`. Is it not yet applicable? Has that command changed to something else? 

I was unable to get help regarding this even after running `splash --help`.

**Comment by Rawnly** [comment]
hi @lalitaalaalitah thanks for reporting this! 
I just created a new PR to restore this option! It should be live within minutes!
