### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by hos4m** [splash-cli/splash-cli#32]
Hi,

Great work on this tool, I'm using it daily now. I was thinking to submit a couple of PRs improving some aspects of the tool and adding a feature that I think it would be appreciated which is an option to clear the `splash_photos` folder by providing a specific argument to the `splash` command.

I couldn't find any guides about how to contribute to the project and how to run it locally.

Thank you :)

**Comment by hos4m** [comment]
Thank you.

**Comment by Rawnly** [comment]
Updated! Check out the **CONTRIBUTING** file.
