### ISSUE TITLE
Version test on linux fails - says 3.0.0 installed when upgraded to 3.0.2

### ISSUE THREAD

**Issue by spacemonkey** [splash-cli/splash-cli#33]
#### Basic informations
- **Splash CLI** version: 3.0.2
- Node version: v8.12.0
- Your OS: Ubuntu 18.10

#### Before you go
- [X] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [X] I've the latest version of **Splash CLI installed**
- [X] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
I upgraded from 3.0.0 to 3.0.2, but when running `splash` the test incorrectly says I am running version 3.0.0 and suggests I update.

**To Reproduce**
1. Run `splash`

**Expected behavior**
I get a lovely wallpaper.

**Console Output**
```
98% 2018-10-23 17:03:28 ⌚  monkeylappy in ~
○ → splash

> woman standing front of body of water

Downloaded: 509 times.
Viewed: 82.3K times.
Liked by 7 users.

Shot by: Matt Lamers (@lamerbrain)




   ╭───────────────────────────────────────╮
   │                                       │
   │    Update available 3.0.0 → 3.0.2     │
   │   Run npm i -g splash-cli to update   │
   │                                       │
   ╰───────────────────────────────────────╯


98% 2018-10-23 17:03:37 ⌚  monkeylappy in ~
○ → splash --version
3.0.2

98% 2018-10-23 17:04:14 ⌚  monkeylappy in ~
○ → node --version
v8.12.0
```

**Comment by Rawnly** [comment]
Have you used npm or yarn? However try to uninstall with both (if you have) and re install again, that happens to me too sometimes. 

I don’t think it’s a splash bug but an “installation path” problem, the bin dir of yarn and npm are different. So if you install splash via yarn and then update it via npm it probably present this type of problem.

Let me know if this works for you
