### ISSUE TITLE
Splash for linux doesn't update wallpaper

### ISSUE THREAD

**Issue by spacemonkey** [splash-cli/splash-cli#34]
#### Basic informations
- **Splash CLI** version: 3.0.2
- Node version: v8.12.0
- Your OS: Ubuntu 18.10

#### Before you go
- [X] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [X] I've the latest version of **Splash CLI installed**
- [X] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
I can run `splash` and see metadata about the image, but it doesn't actually update my wallpaper.

**To Reproduce**
1. Run `splash`

**Expected behavior**
I get a new wallpaper assigned from `splash` command.

**Console Output**
```
98% 2018-10-23 17:03:28 ⌚  monkeylappy in ~
○ → splash

> woman standing front of body of water

Downloaded: 509 times.
Viewed: 82.3K times.
Liked by 7 users.

Shot by: Matt Lamers (@lamerbrain)

98% 2018-10-23 17:08:14 ⌚  monkeylappy in ~
○ → 
```

**Comment by Rawnly** [comment]
In think that [this](https://github.com/sindresorhus/wallpaper/issues/42) is related.

**Comment by Rawnly** [comment]
Unfortunately I can’t test on Linux so thank you for reporting the problem 🔥✌🏻

**Comment by deather** [comment]
Hi,
I'm rewriting the linux part of the lib wallpaper. Maybe it doesn't work because the desktop manager is not manage. Can you say which desktop manager you are using ?

**Comment by Ayanrocks** [comment]
Kde

**Comment by deather** [comment]
There is many way to set KDE, moreover it depends of the version (thank you plasma). If you have some time to spend on it, can you find a command line to change the background ?

Right now we are using qdbus. You can find the command [here](https://github.com/deather/wallpaper/blob/0811726dbd55e4404c5cf44f611105ea95c335e7/lib/linux/background-managers/qdbus.js#L8).

I really appreciate your help on this subject.

**Comment by Ayanrocks** [comment]
Actually I changed it afterwards because of that and reverted to gnome
shell.

**Comment by Rawnly** [comment]
@deather any news?

**Comment by deather** [comment]
@Rawnly Oh sorry I forget to notify you about the new version.

**Comment by Rawnly** [comment]
> @Rawnly Oh sorry I forget to notify you about the new version.

No problem!  So now it's solved?

**Comment by deather** [comment]
I'm not using KDE and I don't have repoduce steps. I think you can close it, and wait if anyone have the problem again.

**Comment by Rawnly** [comment]
Ok perfect, thank you again @deather for the support 💪
