### ISSUE TITLE
Error after update to 3.1.0

### ISSUE THREAD

**Issue by hos4m** [splash-cli/splash-cli#35]
#### Basic informations
- **Splash CLI** version: `3.1.0`
- Node version: `v8.12.0`
- Your OS: **MacOS Mojave**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
After updating `splash-cli` to version 3.1.0, I got this error whenever running the `splash` command in the terminal:
`OAuth error: The access token is invalid`

**Comment by Rawnly** [comment]
I'm working on this, I found a workaround in the meantime, you need to login with your Unsplash account (if you don't have one, [you can create it here](https://unsplash.com/join))

I'm sorry, I'll release an update soon as possible.
