### ISSUE TITLE
Wallpaper not updated when fullscreen app is focused

### ISSUE THREAD

**Issue by hos4m** [splash-cli/splash-cli#36]
#### Basic informations
- **Splash CLI** version: `3.3.0`
- Node version: `v8.12.0`
- Your OS: **Mojave**

# The ISSUE
Picture is not applied as a wallpaper if the focus is on a full screen app.
The picture is downloaded fine but not applied as a wallpaper

**To Reproduce**
1. Run `splash`
2. While it's loading go to a full screen app until the command is done loading
3. Go back to the desktop

**Expected behavior**
After the command finished, the new wallpaper is downloaded but not applied.

**Console Output**
N/A

**Comment by Rawnly** [comment]
Hi 👋, I think that's not a **Splash Cli** issue. More specifically a [wallpaper][wallpaper-repo] related issue.

[wallpaper-repo]: https://github.com/sindresorhus/wallpaper

**Comment by Rawnly** [comment]
Answer by @sindresorhus in [#48](https://github.com/sindresorhus/wallpaper/issues/48#issuecomment-440347144)

> When an app is fullscreen, it's technically in a separate "space". Settings the wallpaper for multiple spaces is not possible, see: [sindresorhus/macos-wallpaper#4](https://github.com/sindresorhus/macos-wallpaper/issues/4)
> 
> Closing as this will need to be fixed by Apple.
