### ISSUE TITLE
v3.3.3 无法获取照片

### ISSUE THREAD

**Issue by SupperLiang** [splash-cli/splash-cli#43]
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:

× { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (d:\Liang\AppData\Roaming\npm\node_modules\splash-cli\node_modules\got\index.js:386:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=undefined&count=1&featured=false',
  protocol: 'https:',
  url:
   'https://api.unsplash.com/photos/random?client_id=undefined&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers':
      'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': '7f4ebf37-987f-4656-87a3-258e2e2f54eb',
     'x-runtime': '0.036429',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Tue, 23 Apr 2019 01:01:57 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2130-IAD, cache-tyo19932-TYO',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1555981317.861780,VS0,VE207',
     vary: 'Origin, Authorization' } }
× Unable to connect.

**Comment by SupperLiang** [comment]
v3.3.1也不行，还是我操作有误，请回复，谢谢

**Comment by Rawnly** [comment]
#38

**Comment by Rawnly** [comment]
If you think that your issue is different please report it in **English**
