### ISSUE TITLE
Support changing on all workspaces for macos

### ISSUE THREAD

**Issue by delfu** [splash-cli/splash-cli#50]
**Is your feature request related to a problem? Please describe.**
On MacOS `--screen all` does not change for all workspaces. Need a way to change background for all workspaces

**Describe the solution you'd like**
on MacOS `--screen all` or `--screen 2` would change the background of the workspace if no other screen is present

**Describe alternatives you've considered**
there's no way i have found to change background for all workspaces.

**Comment by Rawnly** [comment]
Please read FAQ before opening issues. See #17

**Comment by Rawnly** [comment]
This would be cool but splash-cli currently depends on [`wallpaper`](https://github.com/sindresorhus/wallpaper) and technically this would be a feature of the [`wallpaper`](https://github.com/sindresorhus/wallpaper) module

**Comment by Rawnly** [comment]
I was thinking about this issue and the problem you describe it's not actually a problem. You can't change the wallpaper for all workspaces neither from MacOS Preferences app, so there is now way to do that.
