### ISSUE TITLE
Feature: `--screen` option

### ISSUE THREAD

**Issue by reaseno** [splash-cli/splash-cli#55]
In the readme there is an option --screen mentioned, which is gone in the current version (3.4.0). I would like to have that again to manage more screens or exclude a screen from changing wallpaper.

**Comment by Rawnly** [comment]
The screen option is still available, unfortunately is MacOS only. For more info see: [wallpaper](https://github.com/sindresorhus/wallpaper)

**Comment by reaseno** [comment]
As i have no Mac (Windows), its still a feature request for me. Or does it mean it will not be possible?

**Comment by Rawnly** [comment]
I'm sorry but since splash-cli depends on the `wallpaper` package it's not a `splash-cli` feature but a `wallpaper` feature. Unfortunately I don't have enough time to re write the module. If you'd like, I can keep this issue open and hope for someone to contribute.

**Comment by Rawnly** [comment]
You can follow the issue here: [#5](https://github.com/sindresorhus/wallpaper/issues/5)

**Comment by reaseno** [comment]
Sorry, didn't get its a library limitation. Thanks for the info.

**Comment by Rawnly** [comment]
> Sorry, didn't get its a library limitation. Thanks for the info.

Don't worry, no problem ✌️

**Comment by Rawnly** [comment]
I close this issue, and may reopen it in the future when the feature will may be available in the wallpaper module
