### ISSUE TITLE
Feature: `--orientation` option

### ISSUE THREAD

**Issue by reaseno** [splash-cli/splash-cli#56]
**Is your feature request related to a problem? Please describe.**
When downloading a random photo there are also often portrait-oriented pictures. Those look strange on normal landscape-oriented desktop screen.

**Describe the solution you'd like**
There should be an option to specify the orientation of the images. For this you can use the ratio of width to height.

**Comment by Rawnly** [comment]
You can follow updates here [feature/orientation](https://github.com/splash-cli/splash-cli/tree/feature/orientation?files=1)

**Comment by Rawnly** [comment]
Implemented in [`v3.4.5`](https://github.com/splash-cli/splash-cli/releases/3.4.5)
