### ISSUE TITLE
Can't set askForLike property

### ISSUE THREAD

**Issue by EstevaoCostaG3** [splash-cli/splash-cli#66]
#### Basic informations
- **Splash CLI** version: `3.4.10`
- Node version: `8.10.0`
- Your OS: **Ubuntu 18.04 LTS**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
When I run the command `splash settings set askForLike` there's a prompt that asks: "Prompt to like the downloaded photo after download? (Y/n)". I type "n" and hit "Enter", but when I do `splash settings get`, the property "askForLike" is true. And when I run `splash --query wallpaper` it still ask for like.

**To Reproduce**
1. Run `splash settings set askForLike`
2. Type `n` and hit "Enter"

**Expected behavior**
The property "askForLike" should be false in the config file when I run `splash settings get`
**Console Output**
`"askForLike": true,`

**Comment by Rawnly** [comment]
I'll investigate, in the meantime try by setting it via `splash settings` and editing just this property ✌️

**Comment by EstevaoCostaG3** [comment]
> I'll investigate, in the meantime try by setting it via `splash settings` and editing just this property v

Ok. I've tried it, and it worked just fine. 

By the way, I've forked and cloned the repo, but I can't run it locally. I just use `npm run build` followed by `npm run start` passing some flags, like `npm run start --query wallpaper`, but I get an error saying that "wallpaper" isn't a command. And if I don't pass any flags, I get the error "Unable to connect. HTTPError: Response code 401 (Unauthorized)" that comes with a json in the terminal. So, am I building and/or running it the wrong way?

**Comment by Rawnly** [comment]
> So, am I building and/or running it the wrong way?

You're not wrong! You need a `.env` file with the API keys from Unsplash (there's a `.env.example` in the root dir of the project, you can leave blank the `SENTRY_DSN`).
You can get some api keys on [api.unsplash.com](https://unsplash.com/developers)

**Comment by Rawnly** [comment]
If the step above doesn't work try by passing the ENV variables inline like the following: 

```sh
CLIENT_ID=<YOUR_CLIENT_ID> \
CLIENT_SECRET=<YOUR_CLIENT_SECRET> \
yarn build
```

(you can use `npm` as well)

**Comment by EstevaoCostaG3** [comment]
I followed your steps, but still it doesn't working.
I've created an application on unsplash, and they gave me two keys: an `Access Key` and a `Secret key`, as you can see:

![Captura de tela_2020-03-09_13-47-15](https://user-images.githubusercontent.com/22309462/76242380-8d7cb780-622e-11ea-9c3a-ab0020f9874d.png)

I've assigned the the `Access Key` to the variable `CLIENT_ID`; and the `Secret key`, to `CLIENT_SECRET`:
![Captura de tela_2020-03-09_13-53-07](https://user-images.githubusercontent.com/22309462/76242613-e9474080-622e-11ea-8b0f-552cf46e76a9.png)

I don't know why I'm getting the error message: `? Error caught. Would you like to send some feedback?`

**Comment by Rawnly** [comment]
I've tried leaving empty my `.env` and everything works fine to me.. can you publish a screenshot of your terminal?

**Comment by EstevaoCostaG3** [comment]
Now I just cloned my fork again, and I run the these commands (in this order):
`npm i`, `touch .env` (to create a empty `.env` file), `npm run build` and `npm run start`.
The error is as follows:
![Captura de tela_2020-03-10_11-06-58](https://user-images.githubusercontent.com/22309462/76326714-f91f5d00-62e0-11ea-8f2a-9c27c76e290f.png)
![Captura de tela_2020-03-10_11-07-21](https://user-images.githubusercontent.com/22309462/76326735-ffadd480-62e0-11ea-85c3-79dbe2586cf1.png)
Note: this time I've tested it with this configurations:
- Linux Mint 18.1 Serena OS
- node version 8.16.1 
- npm version 6.4.1
