### ISSUE TITLE
Dropping scarf dependency

### ISSUE THREAD

**Issue by samsch** [splash-cli/splash-cli#70]
Heya, we have a community push to get @scarf/scarf removed from packages. It's a data protection and library expectations issue.

There's a considerable backlog of conversation on Reactiflux #news-and-links, with a reasonable starting point here: https://discordapp.com/channels/102860784329052160/105816607976095744/727600754646450206

The conversation also included the author of scarf as well.

The result being tannerlinsley/react-query#676

**Comment by Rawnly** [comment]
✅ Scarf removed successfully, releasing 3.4.12 🔜
