### ISSUE TITLE
Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by reaseno** [splash-cli/splash-cli#82]
Currently the API access seems not possible:

  statusCode: 401,
  statusMessage: 'Unauthorized',

Happens with all unsplash downloads.

**Comment by Rawnly** [comment]
Have you updated from an old version or just installed the latest release?
Which version are you running? Which OS? 

Please before opening a new issue, fill the template.

https://github.com/splash-cli/splash-cli/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by reaseno** [comment]
I always update to the latest version when having problems. And OS should be not relevant for an authentication error. Just my thoughts 😅

With the update I have v3.4.14 and it runs under Win10.

**Comment by reaseno** [comment]
Would it help to set an own API Key? I wonder how I can do that. Haven't found that in the settings yet.

**Comment by Rawnly** [comment]
Unfortunately you're not able to do that

> Would it help to set an own API Key? I wonder how I can do that. Haven't found that in the settings yet.

**Comment by reaseno** [comment]
Thats what I found in your FAQ:
Q: Can I use a custom api-key?
A: Yes, for sure! You can set it in settings.

**Comment by reaseno** [comment]
Can you please give a status? Has your key been banned? Is this the end of the project?

**Comment by Rawnly** [comment]
Hi, my key hasn't been banned, the problem is in the CI that makes the release, for some reason it isn't injecting the api-key, right know I can't find the time to fix this issue, I'm considering re enabling custom api key soon. 

Sorry for late response but I'm full of work

**Comment by Rawnly** [comment]
(The FAQ hasn't been updated)

**Comment by reaseno** [comment]
No problem. Thank you very much for your fast reply 👍

**Comment by Rawnly** [comment]
Hi @reaseno can you confirm that the bug is fixed?

**Comment by reaseno** [comment]
Thank you for get it working again 👍
