### ISSUE TITLE
MacOS multiple desktops

### ISSUE THREAD

**Issue by delfu** [splash-cli/splash-cli#83]
**Is your feature request related to a problem? Please describe.**
Feature request: a flag to support multiple desktops on macos. Currently there's only the support for different monitors and not virtual desktops

**Describe the solution you'd like**
a flag `--desktop` that takes a number or `all` to specify which virtual desktop's background to change

**Describe alternatives you've considered**
today we have to move the terminal to the specific desktop and then run the command to change background for that desktop

**Comment by Rawnly** [comment]
Hi! as #55 I think that this is not a `splash-cli` feature but it might be a  [`wallpaper`](https://github.com/sindresorhus/wallpaper) feature. Btw even in MacOS settings you can't change wallpaper for all virtual desktops at once 😅
