### ISSUE TITLE
...but does it work behind HTTP proxy?

### ISSUE THREAD

**Issue by lwiechec** [splash-cli/splash-cli#9]
### Basic informations
- **splash-cli** version: `2.3.3`
- NodeJs version: `6.9.5`
- Your OS: **Ubuntu**

# ISSUE

I am behind HTTP proxy and `splash-cli` says that there is no internet connection. I _do_ have `http_proxy` and `https_proxy` env, variables set...

**Comment by Rawnly** [comment]
I'll work on it 👍

**Comment by lwiechec** [comment]
Cool! Thanks!!!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Federico VitaleSent: Tuesday, 28 February 2017 10:27To: Rawnly/splash-cliReply To: Rawnly/splash-cliCc: Lukasz Wiechec; AuthorSubject: Re: [Rawnly/splash-cli] ...but does it work behind HTTP proxy? (#9)I'll work on it 👍

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Rawnly/splash-cli","title":"Rawnly/splash-cli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Rawnly/splash-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Rawnly in #9: I'll work on it 👍 "}],"action":{"name":"View Issue","url":"https://github.com/Rawnly/splash-cli/issues/9#issuecomment-282987664"}}}

**Comment by Rawnly** [comment]
:( ithink is a [got](https://github.com/sindresorhus/got) issue... See [this] (https://github.com/sindresorhus/got/issues/7) or [this](https://github.com/sindresorhus/got/issues/79). I'll try with other module, maybe i can add a config for proxed users 👍

**Comment by Rawnly** [comment]
Ok maybe now it's works fine. I'm sorry but i need your help, right now i can't test it behind a proxy.

Clone the `proxy` branch and run `npm install` (or yarn), then set `--proxed` on `true`, and start `cli.js`.

```bash
     $ git clone -b proxy https://github.com/Rawnly/splash-cli.git && cd splash-cli
     $ npm install # or yarn
     $ node cli.js --proxed true
     $ node cli.js
```

Thanks for your patience.

**Comment by lwiechec** [comment]
@Rawnly :) no problem:

I have run all the steps. 
At step number 3 (`node cli.js --proxed true) I got back: `Proxy: true`.
At step number 4 (`node cli.js) I got back: `Splash Error: getaddrinfo ENOTFOUND api.unsplash.com api.unsplash.com:443`

It comes (as far as I can tell) from the fast that `splash-cli` tries to resolve `api.unsplash.com` through default DNS.

As I am behind **very** restrictive proxy (ie. DNS that I have is internal). After I add `api.unsplash.com` to `/etc/hosts` I am getting:

```
⏚ [luke:~/fun/splash-cli]↥ proxy ± node cli.js
true
```

but it times out after ~30 secs and in the end I am getting:

```
Splash Error: connect ECONNREFUSED 151.101.65.7:443
```

I think it means that in the end it is not going through proxy...

**Comment by Rawnly** [comment]
Ok it is as if it were connected to the internet. So i think (again) who it's a problem about `got` module, I'll try with stock `https` module of node

**Comment by Rawnly** [comment]
@lwiechec try to add also `unsplash.com` to your `hosts`

**Comment by lwiechec** [comment]
I tried that. Even with `unsplash.com` the behaviour is the same :(

**Comment by Rawnly** [comment]
@lwiechec keep wait, i'm working on a solution (i hope)!

**Comment by lwiechec** [comment]
:) big thanks for the effort!!





---- On Qua, 01 mar 2017 09:12:27 +0100 Federico Vitale &lt;notifications@github.com&gt; wrote ----




@lwiechec keep wait, i'm working on a solution (i hope)!

**Comment by Rawnly** [comment]
If someone have any ideas on how to fix that feel free to create a new PR or [contact me](mailto:fedevitale99@gmail.com)

**Comment by Rawnly** [comment]
Hey i've got an idea, when splash download the photos, the download link is not `unsplash.com` or `api.unsplash.com` but `images.unsplash.com` who is hosted by [ImgIX](https://www.imgix.com/).

I hope this can be helpful @lwiechec
