### ISSUE TITLE
run splash and nothing happened..

### ISSUE THREAD

**Issue by AngelPone** [splash-cli/splash-cli#90]
![image](https://user-images.githubusercontent.com/32930283/114137911-729fd980-993f-11eb-876e-33a5fe01fcbc.png)

```
(base) ➜  ~ splash -v
3.4.15
(base) ➜  ~ node -v
v15.14.0
```

On macOS Big Sur.

**Comment by AngelPone** [comment]
It worked now, close it.

**Comment by Rawnly** [comment]
it could have been a network problem or an API problem ✌️
